name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Validate gradlew integrity
      uses: gradle/wrapper-validation-action@v1
    - name: Import signing key
      env:
        SIGNING_KEY: ${{ secrets.VIOLET_MOON_SIGNING_KEY }}
      run: echo "${SIGNING_KEY}" | gpg --import -
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}
    - name: Build with Gradle
      run: ./gradlew pmdMain spotlessJavaCheck build
    - name: PMD report
      uses: jwgmeligmeyling/pmd-github-action@v1
      if: failure()
      with:
        path: '**/reports/pmd/main.xml'
    - name: Stop Gradle
      run: |
        ./gradlew stop
    - name: Calculate artifact names
      id: calculate_artifact_names
      run: |
        MC=$(awk -F '=' '/mc_version/ { print $2; }' gradle.properties)
        BUILD=$(awk -F '=' '/build_number/ { print $2; }' gradle.properties)
        echo "forge=Forge/build/libs/Neat-${MC}-${BUILD}-FORGE.jar" >> "$GITHUB_OUTPUT"
        echo "fabric=Fabric/build/libs/Neat-${MC}-${BUILD}-FABRIC.jar" >> "$GITHUB_OUTPUT"
    - name: Sign jars
      run: |
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.forge }}
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.fabric }}
    - name: Archive Forge Jar
      uses: actions/upload-artifact@v2
      with:
        name: Forge Jar
        path: ${{ steps.calculate_artifact_names.outputs.forge }}
    - name: Archive Forge Signature
      uses: actions/upload-artifact@v2
      with:
        name: Forge Signature
        path: ${{ steps.calculate_artifact_names.outputs.forge }}.asc
    - name: Archive Fabric Jar
      uses: actions/upload-artifact@v2
      with:
        name: Fabric Jar
        path: ${{ steps.calculate_artifact_names.outputs.fabric }}
    - name: Archive Fabric Signature
      uses: actions/upload-artifact@v2
      with:
        name: Fabric Signature
        path: ${{ steps.calculate_artifact_names.outputs.fabric }}.asc
